# Generated by Django 5.1.2 on 2024-12-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0006_chatbottopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chatapp.chatbottopic",
            ),
        ),
    ]
