# Generated by Django 5.1.2 on 2025-01-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0008_chat_chatbot_chat_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="documents",
            field=models.FileField(null=True, upload_to="filesd"),
        ),
    ]
